disabled_rules:
  - file_length
  - type_body_length
  - function_body_length
  - force_cast
  - cyclomatic_complexity
  - notification_center_detachment
  - private_over_fileprivate
  - implicit_getter

identifier_name:
  min_length:
    warning: 2

type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 50

nesting:
  type_level: 2
  function_level: 2

line_length: 130
